---
- apt: update_cache=yes
  environment: proxy_env

# Install the package "mysql"
- apt: name={{item}} state=present
  with_items:
   - nginx
   - php5-fpm
   - php5-mysql
  environment: proxy_env

- name: Create nginx configuration file
  template: src=default dest=/etc/nginx/sites-available/default
  notify: 
  - restart nginx

- name: Add wall.php script that demonstrates php and mysql functionality
  template: src=wall.php dest=/usr/share/nginx/html/wall.php

- name: nginx service state
  service: name=nginx state=started enabled=yes
